### ISSUE TITLE
Did CHIPS graduate to Chrome 106?

### ISSUE THREAD

**Issue by surpass-548** [privacycg/CHIPS#57]
Want some clarity. OT said till end of august, and https://developer.chrome.com/docs/privacy-sandbox/chips/ says OT is up to Chrome 105. 
Question: Is CHIPS now generally available? or is it shut down? I can't find updates about this.

**Comment by DCtheTall** [comment]
Hey, thanks for reaching out and apologies for the confusion.

The blog post you are referencing is actually out of date. We have decided to extend the CHIPS Origin Trial to M106+ until October 25th, and unfortunately had to disable the OT in M105 due to a [bug](https://github.com/chromium/chromium/commit/a7b5f82b5c07619336d20758b9f88ea7330034ad) in the implementation. All of this information and future updates are available in the second [Intent to Extend Experiment](https://groups.google.com/a/chromium.org/g/blink-dev/c/MKQODOL0Fso/m/S3ss7A8jCAAJ?utm_medium=email&utm_source=footer) on blink-dev.
