### ISSUE TITLE
Availability of CHIPS wrt user opt-in

### ISSUE THREAD

**Issue by ankwok** [privacycg/CHIPS#77]
Is the access to partitioned storage disabled when a user does not accept the privacy prompt to enable other Privacy Sandbox features (i.e. Topics, PAAPI)?

During the Market Testing period on the portion of browsers with 3PC disabled, and when a user does not opt-in to the Privacy Sandbox, do CHIPS get successfully set?

**Comment by krgovind** [comment]
> Is the access to partitioned storage disabled when a user does not accept the privacy prompt to enable other Privacy Sandbox features (i.e. Topics, PAAPI)?

Partitioned storage and partitioned cookies (CHIPS) are enabled even if a user does not accept the prompt to enable other Privacy Sandbox features; since they do not enable any cross-site transfer of information.

> During the Market Testing period on the portion of browsers with 3PC disabled, and when a user does not opt-in to the Privacy Sandbox, do CHIPS get successfully set?

Yes, they do get set.

As a process note, please use the [privacy-sandbox-dev-support repository](https://github.com/GoogleChromeLabs/privacy-sandbox-dev-support/issues) for Chrome-specific questions.
